version: '3.8'

services:
  postgres:
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    depends_on:
      postgres:
        condition: service_healthy
      eureka:
        condition: service_healthy
