services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    restart: unless-stopped
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/realm-eventos.json:/opt/keycloak/data/import/realm-eventos.json:ro

  db:
    image: postgres:16
    container_name: usuarios_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: usuarios_eventos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - usuarios_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usuarios_eventos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-usuarios:
    build: .
    container_name: ms_usuarios
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      PORT: 8081
      DB_URL: jdbc:postgresql://db:5432/usuarios_eventos_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      # Valida JWT consultando JWKS del Keycloak del compose (evita problemas de issuer)
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/eventos/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    healthcheck:
      # Requiere Actuator: /actuator/health
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health | grep 'UP' >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  usuarios_pg_data:
    driver: local
  keycloak_data:
    driver: local
