version: "3.9"

services:
  db:
    image: postgres:16
    container_name: usuarios_db
    environment:
      POSTGRES_DB: usuarios_eventos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - usuarios_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d usuarios_eventos_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ms-usuarios:
    build: .
    container_name: ms_usuarios
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8081
      DB_URL: jdbc:postgresql://db:5432/usuarios_eventos_db
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    ports:
      - "8081:8081"

volumes:
  usuarios_pg_data:
    driver: local
