spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/notifications_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
