springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  packagesToScan: com.eventos.ms_notifications.controller
  pathsToMatch: /v1/**

api:
  common:
    version: 1.0.0
    title: API Notificaciones
    description: Servicio de gestión de notificaciones de usuarios
    termsOfService: https://www.miempresa.com/terminos
    license: Licencia MIT
    licenseUrl: https://opensource.org/licenses/MIT
    externalDocDesc: Documentación en Wiki
    externalDocUrl: https://www.miempresa.com/wiki
    contact:
      name: Soporte Eventos
      url: https://www.maninthemiddle.com/contacto
      email: soporte@miempresa.com

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, el formato de la solicitud no es válido.
    notFound.description: Not Found, la notificación no existe.
    unauthorized.description: Unauthorized, no tiene permisos para acceder al recurso.
    conflict.description: Conflict, ya existe un recurso con esos datos.
    unprocessableEntity.description: Unprocessable Entity, no se puede procesar la solicitud.

  notification:
    get-by-id:
      summary: Obtener notificación por ID
      description: Retorna una notificación según el ID proporcionado.
      notes: |
        # Respuesta exitosa
        - ID válido, por ejemplo: 1 → 200 OK
        
        # Respuestas con error
        - ID inválido (<= 0), por ejemplo: -1 → 400 Bad Request
        - ID no encontrado, por ejemplo: 100 → 404 Not Found
        - ID no autorizado, por ejemplo: 500 → 401 Unauthorized
      parameters:
        notificationId: ID de la notificación a buscar.

    get-all:
      summary: Listar todas las notificaciones
      description: Obtiene todas las notificaciones registradas.
      notes: |
        # Respuesta exitosa
        - Siempre retorna 200 OK con la lista de notificaciones
        - Lista vacía o con elementos

    create:
      summary: Crear una nueva notificación
      description: Crea una notificación a partir de los datos enviados.
      notes: |
        # Respuesta exitosa
        - DTO válido, por ejemplo userId=200, asunto="Recordatorio", tipoNotificacion="ALERTA" → 200 OK
        
        # Respuestas con error
        - Asunto vacío → 400 Bad Request
        - Mensaje vacío → 400 Bad Request
        - userId no encontrado, por ejemplo: 1111 → 404 Not Found
        - Tipo de notificación conflictivo, por ejemplo: "SISTEMA" → 409 Conflict

    update:
      summary: Actualizar notificación existente
      description: Modifica los datos de una notificación según su ID.
      notes: |
        # Respuesta exitosa
        - ID válido y DTO válido, por ejemplo: ID=10, userId=200, asunto="Actualizado" → 200 OK
        
        # Respuestas con error
        - ID inválido (<=0), por ejemplo: -1 → 400 Bad Request
        - ID no encontrado, por ejemplo: 100 → 404 Not Found
        - ID no autorizado, por ejemplo: 500 → 401 Unauthorized
        - DTO inválido (asunto vacío, mensaje vacío, prioridad incorrecta, etc.) → 400 Bad Request

    delete:
      summary: Eliminar notificación
      description: Elimina una notificación según su ID.
      notes: |
        # Respuesta exitosa
        - ID válido, por ejemplo: 20 → 200 OK
        
        # Respuestas con error
        - ID inválido (<=0), por ejemplo: -1 → 400 Bad Request
        - ID no encontrado, por ejemplo: 100 → 404 Not Found
        - ID no autorizado, por ejemplo: 500 → 401 Unauthorized
